// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/Gishinkou/kker-kratos/backend/coreService/internal/application/userapp"
	"github.com/Gishinkou/kker-kratos/backend/coreService/internal/datarepo/userdata"
	"github.com/Gishinkou/kker-kratos/backend/coreService/internal/domain/service/userdomain"
)

// Injectors from wire.go:

func initUserApp() *userapp.UserApplication {
	iUserRepo := userdata.NewIUserRepo()
	iUserUsecase := userdomain.NewIUserUsecase(iUserRepo)
	userApplication := userapp.NewUserApplication(iUserUsecase)
	return userApplication
}
