// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/Gishinkou/kker-kratos/backend/apiService/internal/applications/userapp"
	"github.com/Gishinkou/kker-kratos/backend/apiService/internal/infrastructure/adapter/baseadapter"
	"github.com/Gishinkou/kker-kratos/backend/apiService/internal/infrastructure/adapter/coreadapter"
)

// Injectors from wire.go:

func initUserApp() *userapp.Application {
	adapter := baseadapter.New()
	coreadapterAdapter := coreadapter.New()
	application := userapp.New(adapter, coreadapterAdapter)
	return application
}
